export default [
  {
    name: 'Yaroslav',
    photo: '../../images/team-photo/yaroslav.jpg',
    instagram: '',
    facebook: '',
    linkedin: '',
    github: '',
  },
  {
    name: 'Anton',
    photo: '../../images/team-photo/anton.jpg',
    instagram: '',
    facebook: '',
    linkedin: '',
    github: '',
  },
  {
    name: 'Alex',
    photo: '../../images/team-photo/alex.jpg',
    instagram: '',
    facebook: '',
    linkedin: '',
    github: '',
  },
  {
    name: 'Artem',
    photo: '../../images/team-photo/artem.jpg',
    instagram: '',
    facebook: 'https://www.facebook.com/artem.sergeev.31/',
    linkedin: 'https://www.linkedin.com/in/artem-sergieiev-447084180/',
    github: 'https://github.com/ArtemS83',
  },
  {
    name: 'Andrii',
    photo: '../../images/team-photo/andrii.jpg',
    instagram: '',
    facebook: '',
    linkedin: 'https://www.linkedin.com/mwlite/in/andrii-stanislav-7ba669201',
    github: 'https://github.com/Andrii-Stanislav',
  },
  {
    name: 'Ihor',
    photo: '../../images/team-photo/ihor.jpg',
    instagram: '',
    facebook: '',
    linkedin: '',
    github: '',
  },
  {
    name: 'Lena',
    photo: '../../images/team-photo/lena.jpg',
    instagram: '',
    facebook: '',
    linkedin: '',
    github: '',
  },
  {
    name: 'Viktoriia',
    photo: '../../images/team-photo/viki.jpg',
    instagram: '',
    facebook: 'https://www.facebook.com/profile.php?id=100011308903028',
    linkedin: 'https://www.linkedin.com/in/viktoriia-ksenofontova/',
    github: 'https://github.com/Viktoriia-Ksenofontova',
  },
   {
    name: 'AntonK',
    photo: '../../images/team-photo/antonk.jpg',
    instagram: '',
    facebook: '',
    linkedin: '',
    github: '',
    },
    {
    name: 'Yehor',
    photo: '../../images/team-photo/yehor.jpg',
    instagram: '',
    facebook: '',
    linkedin: '',
    github: '',
    },
    {
    name: 'Yevheniia',
    photo: '../../images/team-photo/yevheniia.jpg',
    instagram: '',
    facebook: 'https://www.facebook.com/profile.php?id=100024449762426',
    linkedin: 'https://www.linkedin.com/in/evhenya-krot-5837b28/',
    github: 'https://gist.github.com/yevheniia-petrychenko',
    },
    {
    name: 'Miroslava',
    photo: '../../images/team-photo/mira.jpg',
    instagram: 'https://www.instagram.com/mira.nikolaenko',
    facebook: 'https://www.facebook.com/mira.abdulaeva/',
    linkedin: '',
    github: 'https://github.com/Mira1702',
  },
];
