export default [
  {
    name: 'Yaroslav',
    photo: '../../images/team-photo/yaroslav.jpg',
    instagram: 'https://www.instagram.com/mira.nikolaenko',
    facebook: 'https://www.facebook.com/mira.abdulaeva/',
    linkedin: '',
    github: '',
  },
  {
    name: 'Anton',
    photo: '../../images/team-photo/anton.jpg',
    instagram: 'https://www.instagram.com/mira.nikolaenko',
    facebook: 'https://www.facebook.com/mira.abdulaeva/',
    linkedin: '',
    github: '',
  },
  {
    name: 'Alex',
    photo: '../../images/team-photo/alex.jpg',
    instagram: 'https://www.instagram.com/mira.nikolaenko',
    facebook: 'https://www.facebook.com/mira.abdulaeva/',
    linkedin: '',
    github: '',
  },
  {
    name: 'Artem',
    photo: '../../images/team-photo/artem.jpg',
    instagram: 'https://www.instagram.com/mira.nikolaenko',
    facebook: 'https://www.facebook.com/mira.abdulaeva/',
    linkedin: '',
    github: '',
  },
  {
    name: 'Andrii',
    photo: '../../images/team-photo/andrii.jpg',
    instagram: 'https://www.instagram.com/mira.nikolaenko',
    facebook: 'https://www.facebook.com/mira.abdulaeva/',
    linkedin: '',
    github: '',
  },
  {
    name: 'Ihor',
    photo: '../../images/team-photo/ihor.jpg',
    instagram: 'https://www.instagram.com/mira.nikolaenko',
    facebook: 'https://www.facebook.com/mira.abdulaeva/',
    linkedin: '',
    github: '',
  },
  {
    name: 'Lena',
    photo: '../../images/team-photo/lena.jpg',
    instagram: 'https://www.instagram.com/mira.nikolaenko',
    facebook: 'https://www.facebook.com/mira.abdulaeva/',
    linkedin: '',
    github: '',
  },
  {
    name: 'Viki',
    photo: '../../images/team-photo/viki.jpg',
    instagram: 'https://www.instagram.com/mira.nikolaenko',
    facebook: 'https://www.facebook.com/mira.abdulaeva/',
    linkedin: '',
    github: '',
  },
   {
    name: 'AntonK',
    photo: '../../images/team-photo/antonk.jpg',
    instagram: 'https://www.instagram.com/mira.nikolaenko',
    facebook: 'https://www.facebook.com/mira.abdulaeva/',
    linkedin: '',
    github: '',
    },
    {
    name: 'Yehor',
    photo: '../../images/team-photo/yehor.jpg',
    instagram: 'https://www.instagram.com/mira.nikolaenko',
    facebook: 'https://www.facebook.com/mira.abdulaeva/',
    linkedin: '',
    github: '',
    },
    {
    name: 'Yevheniia',
    photo: '../../images/team-photo/yevheniia.jpg',
    instagram: 'https://www.instagram.com/mira.nikolaenko',
    facebook: 'https://www.facebook.com/mira.abdulaeva/',
    linkedin: '',
    github: '',
    },
    {
    name: 'Miroslava',
    photo: '../../images/team-photo/mira.jpg',
    instagram: 'https://www.instagram.com/mira.nikolaenko',
    facebook: 'https://www.facebook.com/mira.abdulaeva/',
    linkedin: '',
    github: '',
  },
];
